export const FLAVOR_CONFIG = {
  // --- FRUITY (Red/Orange Family) ---
  // Berry (#ED2C4B)
  '딸기': { color: '#ED2C4B', textColor: '#ffffff' }, 
  '라즈베리': { color: '#ED2C4B', textColor: '#ffffff' }, 
  '블루베리': { color: '#ED2C4B', textColor: '#ffffff' }, 
  '블랙베리': { color: '#ED2C4B', textColor: '#ffffff' },
  '믹스베리': { color: '#ED2C4B', textColor: '#ffffff' },
  '건크랜베리': { color: '#ED2C4B', textColor: '#ffffff' },
  '크랜베리': { color: '#ED2C4B', textColor: '#ffffff' },
  
  // Dried Fruit (#D7444F)
  '건포도': { color: '#D7444F', textColor: '#ffffff' }, 
  '무화과': { color: '#D7444F', textColor: '#ffffff' },
  '자두': { color: '#D7444F', textColor: '#ffffff' }, 
  '살구': { color: '#D7444F', textColor: '#ffffff' },
  '대추': { color: '#D7444F', textColor: '#ffffff' },

  // Other Fruit (#F26648)
  '코코넛': { color: '#F26648', textColor: '#ffffff' },
  '체리': { color: '#F26648', textColor: '#ffffff' },
  '석류': { color: '#F26648', textColor: '#ffffff' },
  '파인애플': { color: '#F26648', textColor: '#ffffff' },
  '망고': { color: '#F26648', textColor: '#ffffff' },
  '패션후르츠': { color: '#F26648', textColor: '#ffffff' },
  '리치': { color: '#F26648', textColor: '#ffffff' },
  '복숭아': { color: '#F26648', textColor: '#ffffff' },
  '배': { color: '#F26648', textColor: '#ffffff' },
  '포도': { color: '#F26648', textColor: '#ffffff' },
  '적포도': { color: '#F26648', textColor: '#ffffff' },
  '멜론': { color: '#F26648', textColor: '#ffffff' },
  '사과': { color: '#F26648', textColor: '#ffffff' },
  '청사과': { color: '#F26648', textColor: '#ffffff' },

  // Citrus Fruit (#FCB914)
  '자몽': { color: '#FCB914', textColor: '#111111' },
  '오렌지': { color: '#FCB914', textColor: '#111111' },
  '레몬': { color: '#FCB914', textColor: '#111111' },
  '라임': { color: '#FCB914', textColor: '#111111' },
  '귤': { color: '#FCB914', textColor: '#111111' },
  '베르가못': { color: '#FCB914', textColor: '#111111' },
  '청포도': { color: '#FCB914', textColor: '#111111' },
  '깔라만시': { color: '#FCB914', textColor: '#111111' },

  // --- FLORAL (#EC008C) ---
  '꽃': { color: '#EC008C', textColor: '#ffffff' },
  '자스민': { color: '#EC008C', textColor: '#ffffff' },
  '장미': { color: '#EC008C', textColor: '#ffffff' },
  '카모마일': { color: '#EC008C', textColor: '#ffffff' },
  '히비스커스': { color: '#EC008C', textColor: '#ffffff' },
  '아카시아': { color: '#EC008C', textColor: '#ffffff' },
  '라벤더': { color: '#EC008C', textColor: '#ffffff' },
  '오렌지 블로썸': { color: '#EC008C', textColor: '#ffffff' },
  '국화': { color: '#EC008C', textColor: '#ffffff' },

  // --- SWEET (#F36421) ---
  '바닐라': { color: '#F36421', textColor: '#ffffff' },
  '달콤함': { color: '#F36421', textColor: '#ffffff' },
  '흑설탕': { color: '#F36421', textColor: '#ffffff' },
  '백설탕': { color: '#F36421', textColor: '#ffffff' },
  '당밀': { color: '#F36421', textColor: '#ffffff' },
  '메이플시럽': { color: '#F36421', textColor: '#ffffff' },
  '시럽': { color: '#F36421', textColor: '#ffffff' },
  '캐러멜': { color: '#F36421', textColor: '#ffffff' },
  '꿀': { color: '#F36421', textColor: '#ffffff' },
  '아카시아 꿀': { color: '#F36421', textColor: '#ffffff' },
  '잡화 꿀': { color: '#F36421', textColor: '#ffffff' },
  '밀크시럽': { color: '#F36421', textColor: '#ffffff' },
  '마시멜로': { color: '#F36421', textColor: '#ffffff' },

  // --- NUTTY/COCOA (#9A7B79) ---
  '초콜릿': { color: '#9A7B79', textColor: '#ffffff' },
  '다크 초콜릿': { color: '#9A7B79', textColor: '#ffffff' },
  '밀크 초콜릿': { color: '#9A7B79', textColor: '#ffffff' },
  '화이트 초콜릿': { color: '#9A7B79', textColor: '#ffffff' },
  '카카오': { color: '#9A7B79', textColor: '#ffffff' },
  '견과류': { color: '#9A7B79', textColor: '#ffffff' },
  '아몬드': { color: '#9A7B79', textColor: '#ffffff' },
  '구운 아몬드': { color: '#9A7B79', textColor: '#ffffff' },
  '헤이즐넛': { color: '#9A7B79', textColor: '#ffffff' },
  '땅콩': { color: '#9A7B79', textColor: '#ffffff' },
  '피넛': { color: '#9A7B79', textColor: '#ffffff' },
  '호두': { color: '#9A7B79', textColor: '#ffffff' },
  '캐슈넛': { color: '#9A7B79', textColor: '#ffffff' },
  '피스타치오': { color: '#9A7B79', textColor: '#ffffff' },

  // --- SPICES (#B90D41) ---
  '정향': { color: '#B90D41', textColor: '#ffffff' },
  '계피': { color: '#B90D41', textColor: '#ffffff' },
  '시나몬': { color: '#B90D41', textColor: '#ffffff' },
  '육두구': { color: '#B90D41', textColor: '#ffffff' },
  '후추': { color: '#B90D41', textColor: '#ffffff' },
  '블랙 페퍼': { color: '#B90D41', textColor: '#ffffff' },
  '생강': { color: '#B90D41', textColor: '#ffffff' },

  // --- ROASTED (#D33727) ---
  '담배': { color: '#D33727', textColor: '#ffffff' },
  '곡류': { color: '#D33727', textColor: '#ffffff' },
  '보리': { color: '#D33727', textColor: '#ffffff' },
  '구운 빵': { color: '#D33727', textColor: '#ffffff' },
  '시리얼': { color: '#D33727', textColor: '#ffffff' },
  '호밀': { color: '#D33727', textColor: '#ffffff' },
  '맥아': { color: '#D33727', textColor: '#ffffff' },
  '볶은 곡물': { color: '#D33727', textColor: '#ffffff' },
  '탄': { color: '#000000', textColor: '#ffffff' },

  // --- GREEN/VEGETATIVE (#17803B) ---
  '풀내음': { color: '#17803B', textColor: '#ffffff' },
  '허브': { color: '#17803B', textColor: '#ffffff' },
  '민트': { color: '#17803B', textColor: '#ffffff' },
  '세이지': { color: '#17803B', textColor: '#ffffff' },
  '로즈마리': { color: '#17803B', textColor: '#ffffff' },
  '딜': { color: '#17803B', textColor: '#ffffff' },
  '레몬그라스': { color: '#17803B', textColor: '#ffffff' },

  // --- SOUR/FERMENTED (#F5CE02) ---
  '와인': { color: '#F5CE02', textColor: '#111111' },
  '위스키': { color: '#F5CE02', textColor: '#111111' },
  '와이니한': { color: '#F5CE02', textColor: '#111111' }, 

  // --- OTHER (#00A7D2) ---
  '화학': { color: '#00A7D2', textColor: '#ffffff' },
  '고무': { color: '#00A7D2', textColor: '#ffffff' },
  '버터': { color: '#00A7D2', textColor: '#ffffff' },
  '크림': { color: '#00A7D2', textColor: '#ffffff' },
  '치즈': { color: '#00A7D2', textColor: '#ffffff' },
  '요거트': { color: '#00A7D2', textColor: '#ffffff' },

  // --- NON-WHEEL DESCRIPTORS (Black Background) ---
  '긴 여운': { color: '#000000', textColor: '#ffffff' },
  '깔끔한 마무리': { color: '#000000', textColor: '#ffffff' },
  '달콤한 잔향': { color: '#000000', textColor: '#ffffff' },
  '차와 같은': { color: '#000000', textColor: '#ffffff' },
  '밝은 산미': { color: '#000000', textColor: '#ffffff' },
  '섬세한 산미': { color: '#000000', textColor: '#ffffff' },
  '실키한 바디': { color: '#000000', textColor: '#ffffff' },
  '벨벳 같은': { color: '#000000', textColor: '#ffffff' },
  '주스 같은': { color: '#000000', textColor: '#ffffff' },
  '크리미한': { color: '#000000', textColor: '#ffffff' },
  '시리얼 같은': { color: '#D33727', textColor: '#ffffff' },
  '단맛의 균형': { color: '#000000', textColor: '#ffffff' },
  '뛰어난 균형감': { color: '#000000', textColor: '#ffffff' },
  '조화로운': { color: '#000000', textColor: '#ffffff' },
  '투명한': { color: '#000000', textColor: '#ffffff' },
  '정돈된': { color: '#000000', textColor: '#ffffff' },
  '깔끔한 클린컵': { color: '#000000', textColor: '#ffffff' },
};

export const countryToCode = {
  // South & Central America
  '브라질': 'br', 'brazil': 'br', 'Brazil': 'br',
  '콜롬비아': 'co', 'colombia': 'co', 'Colombia': 'co',
  '파나마': 'pa', 'panama': 'pa', 'Panama': 'pa',
  '과테말라': 'gt', 'guatemala': 'gt', 'Guatemala': 'gt',
  '코스타리카': 'cr', 'costa rica': 'cr', 'Costa Rica': 'cr',
  '온두라스': 'hn', 'honduras': 'hn', 'Honduras': 'hn',
  '에콰도르': 'ec', 'ecuador': 'ec', 'Ecuador': 'ec',
  '엘살바도르': 'sv', 'el salvador': 'sv', 'El Salvador': 'sv',
  '니카라과': 'ni', 'nicaragua': 'ni', 'Nicaragua': 'ni',
  '멕시코': 'mx', 'mexico': 'mx', 'Mexico': 'mx',
  '페루': 'pe', 'peru': 'pe', 'Peru': 'pe',
  '볼리비아': 'bo', 'bolivia': 'bo', 'Bolivia': 'bo',
  '도미니카 공화국': 'do', 'dominican republic': 'do', 'Dominican Republic': 'do',
  '자메이카': 'jm', 'jamaica': 'jm', 'Jamaica': 'jm',
  // Africa
  '에티오피아': 'et', 'ethiopia': 'et', 'Ethiopia': 'et',
  '케냐': 'ke', 'kenya': 'ke', 'Kenya': 'ke',
  '탄자니아': 'tz', 'tanzania': 'tz', 'Tanzania': 'tz',
  '르완다': 'rw', 'rwanda': 'rw', 'Rwanda': 'rw',
  '부룬디': 'bi', 'burundi': 'bi', 'Burundi': 'bi',
  '우간다': 'ug', 'uganda': 'ug', 'Uganda': 'ug',
  '콩고민주공화국': 'cd', 'dr congo': 'cd', 'DR Congo': 'cd', 'congo': 'cd',
  '말라위': 'mw', 'malawi': 'mw', 'Malawi': 'mw',
  '잠비아': 'zm', 'zambia': 'zm', 'Zambia': 'zm',
  // Asia & Middle East
  '예멘': 'ye', 'yemen': 'ye', 'Yemen': 'ye',
  '베트남': 'vn', 'vietnam': 'vn', 'Vietnam': 'vn',
  '인도네시아': 'id', 'indonesia': 'id', 'Indonesia': 'id',
  '인도': 'in', 'india': 'in', 'India': 'in',
  '태국': 'th', 'thailand': 'th', 'Thailand': 'th',
  '라오스': 'la', 'laos': 'la', 'Laos': 'la',
  '파푸아뉴기니': 'pg', 'papua new guinea': 'pg', 'Papua New Guinea': 'pg',
  '필리핀': 'ph', 'philippines': 'ph', 'Philippines': 'ph',
  '동티모르': 'tl', 'east timor': 'tl', 'East Timor': 'tl',
  '미얀마': 'mm', 'myanmar': 'mm', 'Myanmar': 'mm',
  '중국': 'cn', 'china': 'cn', 'China': 'cn',
  // Others
  '미국': 'us', 'usa': 'us', 'USA': 'us', 'United States': 'us',
  '한국': 'kr', 'korea': 'kr', 'Korea': 'kr', 'South Korea': 'kr'
};
